import Link from 'next/link';
import { fetchStationForecast, fetchModelMetadata } from '@/lib/api';

export const dynamic = 'force-dynamic';

interface PageProps {
  searchParams?: {
    station?: string;
  };
}

export default async function ForecastPage({ searchParams }: PageProps) {
  const selectedStation = searchParams?.station || 'DL_ANAND_VIHAR';
  const [forecast, modelsMeta] = await Promise.all([
    fetchStationForecast(selectedStation),
    fetchModelMetadata()
  ]);

  const stationsList = [
    { code: 'DL_ANAND_VIHAR', name: 'Anand Vihar (East)' },
    { code: 'DL_PUNJABI_BAGH', name: 'Punjabi Bagh (West)' },
    { code: 'DL_RK_PURAM', name: 'R.K. Puram (South)' },
    { code: 'DL_IGI_AIRPORT', name: 'IGI Airport (Southwest)' },
    { code: 'DL_BAWANA', name: 'Bawana (Northwest)' },
  ];

  return (
    <div className="container">
      {/* Header */}
      <div style={{ marginBottom: '2rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem', flexWrap: 'wrap' }}>
          <span className="badge badge-success">Phase 4 Operational</span>
          <span className="badge badge-info">LightGBM Direct Multi-Horizon</span>
          <span className="badge badge-neutral">
            Initialized from Real Ground Telemetry
          </span>
        </div>
        <h1 style={{ fontSize: '2.25rem', fontWeight: 800 }}>72-Hour Air Quality Forecast Horizons</h1>
        <p style={{ color: 'var(--text-secondary)', marginTop: '0.5rem', maxWidth: '750px' }}>
          Multi-horizon PM2.5 forecasts generated by direct LightGBM models trained on verified historical observations.
          Evaluated against held-out winter test partitions with zero forward-looking leakage.
        </p>
      </div>

      {/* Station Selector Bar */}
      <div className="glass-panel" style={{ padding: '1rem', marginBottom: '2rem', display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
        <span style={{ fontSize: '0.875rem', fontWeight: 600, color: 'var(--text-secondary)' }}>Select Anchor Station:</span>
        <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
          {stationsList.map((stn) => (
            <Link
              key={stn.code}
              href={`/forecast?station=${stn.code}`}
              className="badge"
              style={{
                padding: '0.5rem 0.85rem',
                textDecoration: 'none',
                backgroundColor: selectedStation === stn.code ? 'var(--accent-cyan)' : 'var(--bg-card-hover)',
                color: selectedStation === stn.code ? '#ffffff' : 'var(--text-secondary)',
                fontWeight: selectedStation === stn.code ? 700 : 600,
                border: '1px solid var(--border-subtle)',
                transition: 'all 0.2s ease'
              }}
            >
              {stn.name}
            </Link>
          ))}
        </div>
      </div>

      {/* Station Metadata & Initial State */}
      {forecast && forecast.status === 'SUCCESS' ? (
        <>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1rem', marginBottom: '2rem' }}>
            <div className="glass-panel" style={{ padding: '1rem' }}>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Station</div>
              <div style={{ fontSize: '1.25rem', fontWeight: 700, marginTop: '0.25rem' }}>{forecast.station_name}</div>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{forecast.station_code}</div>
            </div>

            <div className="glass-panel" style={{ padding: '1rem' }}>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Latest Observed PM2.5</div>
              <div style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '0.25rem', color: 'var(--accent-emerald)' }}>
                {forecast.latest_observed_pm25} µg/m³
              </div>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Baseline Observation Anchor</div>
            </div>

            <div className="glass-panel" style={{ padding: '1rem' }}>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Forecast Initialized</div>
              <div style={{ fontSize: '1rem', fontWeight: 600, marginTop: '0.25rem' }}>
                {new Date(forecast.initialization_time_utc).toLocaleString()}
              </div>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>UTC Reference Time</div>
            </div>

            <div className="glass-panel" style={{ padding: '1rem' }}>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Models Active</div>
              <div style={{ fontSize: '1rem', fontWeight: 600, marginTop: '0.25rem', color: 'var(--accent-cyan)' }}>
                LightGBM (7 Horizons)
              </div>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>+ Naive Persistence Baseline</div>
            </div>
          </div>

          {/* 72-Hour Forecast Curve Cards */}
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '1rem' }}>
            Discrete Multi-Horizon Forecast Trajectory
          </h2>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '1rem', marginBottom: '2.5rem' }}>
            {forecast.forecast_horizons.map((step) => {
              const aqiColor =
                step.derived_aqi <= 50 ? '#10b981' :
                step.derived_aqi <= 100 ? '#84cc16' :
                step.derived_aqi <= 200 ? '#f59e0b' :
                step.derived_aqi <= 300 ? '#f97316' :
                step.derived_aqi <= 400 ? '#ef4444' : '#7f1d1d';

              return (
                <div key={step.horizon_hours} className="glass-panel" style={{ padding: '1.25rem', borderTop: `4px solid ${aqiColor}` }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                    <span style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--accent-cyan)' }}>
                      +{step.horizon_hours}h Horizon
                    </span>
                    <span
                      style={{
                        padding: '0.2rem 0.5rem',
                        borderRadius: '4px',
                        fontSize: '0.75rem',
                        fontWeight: 700,
                        backgroundColor: `${aqiColor}22`,
                        color: aqiColor
                      }}
                    >
                      AQI {step.derived_aqi}
                    </span>
                  </div>

                  <div style={{ fontSize: '2rem', fontWeight: 800, fontFamily: 'var(--font-heading)', margin: '0.5rem 0' }}>
                    {step.predicted_pm25_ugm3} <span style={{ fontSize: '0.9rem', fontWeight: 500, color: 'var(--text-muted)' }}>µg/m³</span>
                  </div>

                  <div style={{ fontSize: '0.8rem', color: aqiColor, fontWeight: 600 }}>
                    Category: {step.aqi_category}
                  </div>

                  <div style={{ marginTop: '0.75rem', paddingTop: '0.75rem', borderTop: '1px solid var(--border-subtle)', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                    <div>Target: {new Date(step.target_time_utc).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} ({new Date(step.target_time_utc).toLocaleDateString()})</div>
                    <div style={{ marginTop: '0.25rem', color: '#64748b' }}>Engine: {step.model_type}</div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Benchmark Models Comparison Table */}
          <div style={{ marginBottom: '2.5rem' }}>
            <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.75rem' }}>
              Phase 4 Benchmark Comparison Table (Held-Out Test Set: Feb 2024)
            </h2>
            <div className="glass-panel" style={{ overflowX: 'auto', padding: '0.5rem' }}>
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Model Architecture</th>
                    <th>+1h MAE</th>
                    <th>+3h MAE</th>
                    <th>+6h MAE</th>
                    <th>+12h MAE</th>
                    <th>+24h MAE</th>
                    <th>+48h MAE</th>
                    <th>+72h MAE</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style={{ fontWeight: 600 }}>Baseline 1: Naive Persistence</td>
                    <td style={{ padding: '0.75rem 1rem' }}>9.26</td>
                    <td style={{ padding: '0.75rem 1rem' }}>15.81</td>
                    <td style={{ padding: '0.75rem 1rem' }}>20.19</td>
                    <td style={{ padding: '0.75rem 1rem' }}>20.65</td>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 700, color: 'var(--accent-emerald)' }}>18.67</td>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 700, color: 'var(--accent-emerald)' }}>21.27</td>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 700, color: 'var(--accent-emerald)' }}>22.17</td>
                  </tr>
                  <tr>
                    <td style={{ fontWeight: 600 }}>Baseline 2: Diurnal Statistical</td>
                    <td style={{ padding: '0.75rem 1rem' }}>17.89</td>
                    <td style={{ padding: '0.75rem 1rem' }}>18.40</td>
                    <td style={{ padding: '0.75rem 1rem' }}>19.06</td>
                    <td style={{ padding: '0.75rem 1rem' }}>20.21</td>
                    <td style={{ padding: '0.75rem 1rem' }}>21.53</td>
                    <td style={{ padding: '0.75rem 1rem' }}>22.88</td>
                    <td style={{ padding: '0.75rem 1rem' }}>24.86</td>
                  </tr>
                  <tr>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 600, color: 'var(--accent-cyan)' }}>Baseline 3: LightGBM Multi-Horizon</td>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 700, color: 'var(--accent-cyan)' }}>6.69 (-28%)</td>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 700, color: 'var(--accent-cyan)' }}>10.21 (-35%)</td>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 700, color: 'var(--accent-cyan)' }}>15.37 (-24%)</td>
                    <td style={{ padding: '0.75rem 1rem', fontWeight: 700, color: 'var(--accent-cyan)' }}>17.36 (-16%)</td>
                    <td style={{ padding: '0.75rem 1rem' }}>21.15</td>
                    <td style={{ padding: '0.75rem 1rem' }}>28.44</td>
                    <td style={{ padding: '0.75rem 1rem' }}>32.02</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '0.5rem' }}>
              * LightGBM decisively wins at +1h to +12h. Beyond 24h, local autoregressive features decay, mathematically demonstrating why Phase 5 forward numerical plume advection is mandatory.
            </p>
          </div>
        </>
      ) : (
        <div className="empty-state">
          <div className="empty-icon">&#9888;</div>
          <div className="empty-title">Forecast Data Unavailable for {selectedStation}</div>
          <div className="empty-desc">
            The backend forecasting service did not return predictions for this station identifier.
            Ensure the FastAPI server is running at <code>http://localhost:8000</code> and the Phase 4 training pipeline has been executed.
          </div>
        </div>
      )}

      {/* Back link */}
      <div>
        <Link href="/" style={{ color: 'var(--accent-cyan)', fontSize: '0.9rem', textDecoration: 'none' }}>
          &larr; Return to Command Center
        </Link>
      </div>
    </div>
  );
}
